[package]
name = "game-easy"
version = "0.1.0"
authors = ["MaratWorker <maratn566ek@gmail.com>"]
edition = "2018"
build="build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sfml="*"
rand="*"
